version: '3.1'

services:

  front:
    build:
      context: .

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    depends_on:
      - front
    volumes:
      - ./config:/config
      - ./default:/config/nginx/site-confs/default
    environment:
      - EMAIL=ntvelezd@eafit.edu.co
      - URL=www.retodostelematica.tk
      - VALIDATION=http
      - TZ=Europe/London
      - PUID=500
      - PGID=500
    ports:
      - "443:443"
      - "80:80"

volumes:
  front:
